package Ejercicios.Tarea;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author USUARIO
 */
public class Tarea_11 extends javax.swing.JFrame {

    /**
     * Creates new form Ejercicio_01
     */
    public Tarea_11() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        TXT_PRIME = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        TXT_SEGUN = new javax.swing.JTextField();
        BTN_CIR = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        TXT_RESUL = new javax.swing.JTextField();
        BTN_CUA = new javax.swing.JButton();
        BTN_REC = new javax.swing.JButton();
        BTN_TRIAN = new javax.swing.JButton();
        BTN_LIM = new javax.swing.JButton();
        BTN_SALIR = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 204, 204));

        jLabel1.setBackground(new java.awt.Color(0, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 0));
        jLabel1.setText("Calcular las áreas");

        jLabel2.setText("PRIMER NÚMERO:");

        TXT_PRIME.setBackground(new java.awt.Color(255, 255, 51));
        TXT_PRIME.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXT_PRIMEActionPerformed(evt);
            }
        });

        jLabel3.setText("SEGUNDO NÚMERO:");

        TXT_SEGUN.setBackground(new java.awt.Color(255, 255, 51));
        TXT_SEGUN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXT_SEGUNActionPerformed(evt);
            }
        });

        BTN_CIR.setBackground(new java.awt.Color(153, 255, 153));
        BTN_CIR.setText("ÁREA DEL CÍRCULO");
        BTN_CIR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_CIRActionPerformed(evt);
            }
        });

        jLabel4.setText("RESULTADO");

        TXT_RESUL.setBackground(new java.awt.Color(204, 255, 102));
        TXT_RESUL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXT_RESULActionPerformed(evt);
            }
        });

        BTN_CUA.setBackground(new java.awt.Color(51, 255, 204));
        BTN_CUA.setText("ÁREA DEL CUADRADO");
        BTN_CUA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_CUAActionPerformed(evt);
            }
        });

        BTN_REC.setBackground(new java.awt.Color(0, 0, 255));
        BTN_REC.setText("ÁREA DEL RECTÁNGULO");
        BTN_REC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_RECActionPerformed(evt);
            }
        });

        BTN_TRIAN.setBackground(new java.awt.Color(255, 51, 51));
        BTN_TRIAN.setText("ÁREA DEL TRIÁNGULO");
        BTN_TRIAN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_TRIANActionPerformed(evt);
            }
        });

        BTN_LIM.setText("LIMPIAR");
        BTN_LIM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_LIMActionPerformed(evt);
            }
        });

        BTN_SALIR.setText("SALIR");
        BTN_SALIR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_SALIRActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(160, 160, 160)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(TXT_PRIME, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                                    .addComponent(TXT_SEGUN)
                                    .addComponent(TXT_RESUL))
                                .addGap(91, 91, 91)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(BTN_REC)
                                    .addComponent(BTN_CUA)
                                    .addComponent(BTN_CIR)
                                    .addComponent(BTN_TRIAN)
                                    .addComponent(BTN_LIM)
                                    .addComponent(BTN_SALIR))))))
                .addContainerGap(160, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TXT_PRIME, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(65, 65, 65)
                                .addComponent(BTN_CIR)))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3))
                    .addComponent(BTN_CUA, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(TXT_SEGUN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(BTN_REC)))
                .addGap(18, 18, 18)
                .addComponent(BTN_TRIAN)
                .addGap(7, 7, 7)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TXT_RESUL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BTN_LIM))
                .addGap(18, 18, 18)
                .addComponent(BTN_SALIR)
                .addContainerGap(77, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BTN_TRIANActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_TRIANActionPerformed
        String prime = TXT_PRIME.getText();
        String segun = TXT_SEGUN.getText();

        double primeNum = Double.parseDouble(prime);
        double segunNum = Double.parseDouble(segun);

        double area = (primeNum * segunNum) / 2;

        TXT_RESUL.setText(String.format("%.2f", area));    }//GEN-LAST:event_BTN_TRIANActionPerformed

    private void TXT_PRIMEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXT_PRIMEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXT_PRIMEActionPerformed

    private void TXT_SEGUNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXT_SEGUNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXT_SEGUNActionPerformed

    private void TXT_RESULActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXT_RESULActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXT_RESULActionPerformed

    private void BTN_RECActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_RECActionPerformed
        String prime = TXT_PRIME.getText();
        String segun = TXT_SEGUN.getText();

        double primeNum = Double.parseDouble(prime);
        double segunNum = Double.parseDouble(segun);

        double area = primeNum * segunNum;

        TXT_RESUL.setText(String.format("%.2f", area));    }//GEN-LAST:event_BTN_RECActionPerformed

    private void BTN_CUAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_CUAActionPerformed
        String prime = TXT_PRIME.getText();

        double primeNum = Double.parseDouble(prime);

        double area = Math.pow(primeNum, 2);

        TXT_RESUL.setText(String.format("%.2f", area));    }//GEN-LAST:event_BTN_CUAActionPerformed

    private void BTN_CIRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_CIRActionPerformed
        String prime = TXT_PRIME.getText();

        double primeNum = Double.parseDouble(prime);

        double area = Math.PI * Math.pow(primeNum, 2);

        TXT_RESUL.setText(String.format("%.2f", area));    }//GEN-LAST:event_BTN_CIRActionPerformed

    private void BTN_SALIRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_SALIRActionPerformed
        System.exit(0);
    }//GEN-LAST:event_BTN_SALIRActionPerformed

    private void BTN_LIMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_LIMActionPerformed
        TXT_PRIME.setText("");
        TXT_SEGUN.setText("");
        TXT_RESUL.setText("");    }//GEN-LAST:event_BTN_LIMActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tarea_11.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tarea_11.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tarea_11.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tarea_11.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tarea_11().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTN_CIR;
    private javax.swing.JButton BTN_CUA;
    private javax.swing.JButton BTN_LIM;
    private javax.swing.JButton BTN_REC;
    private javax.swing.JButton BTN_SALIR;
    private javax.swing.JButton BTN_TRIAN;
    private javax.swing.JTextField TXT_PRIME;
    private javax.swing.JTextField TXT_RESUL;
    private javax.swing.JTextField TXT_SEGUN;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
