package Ejercicios.Tarea;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author USUARIO
 */
public class Tarea_13 extends javax.swing.JFrame {

    /**
     * Creates new form Ejercicio_03
     */
    public Tarea_13() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        LB_NOR = new javax.swing.JLabel();
        LB_PREM = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        TXT_TIPO = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        TXT_CANT = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        TXT_TOTAL = new javax.swing.JTextField();
        BTN_TOTAL = new javax.swing.JButton();
        BTN_SALIR = new javax.swing.JButton();
        BTN_BOR = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("ESTACIÓN DE TRENES");

        LB_NOR.setText("1. PASAJE NORMAL = S/.25");

        LB_PREM.setText("2. PASAJE PREMIUM = S/. 70");

        jLabel3.setText("¿QUÉ TIPO DE TICKET DESEA COMPRAR?");

        TXT_TIPO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXT_TIPOActionPerformed(evt);
            }
        });

        jLabel4.setText("¿CUÁNTAS ENTRADAS VA A COMPRAR?");

        TXT_CANT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXT_CANTActionPerformed(evt);
            }
        });

        jLabel5.setText("TOTAL A PAGAR ES:");

        TXT_TOTAL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXT_TOTALActionPerformed(evt);
            }
        });

        BTN_TOTAL.setText("TOTAL A PAGAR");
        BTN_TOTAL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_TOTALActionPerformed(evt);
            }
        });

        BTN_SALIR.setText("SALIR");
        BTN_SALIR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_SALIRActionPerformed(evt);
            }
        });

        BTN_BOR.setText("LIMPIAR");
        BTN_BOR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_BORActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LB_PREM)
                            .addComponent(LB_NOR)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(TXT_TOTAL, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(34, 34, 34)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(TXT_TIPO)
                                            .addComponent(TXT_CANT))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(BTN_TOTAL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(BTN_SALIR, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(BTN_BOR))))))
                .addGap(42, 42, 42))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(LB_NOR)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(LB_PREM)
                .addGap(46, 46, 46)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TXT_TIPO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BTN_BOR))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BTN_SALIR))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TXT_CANT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TXT_TOTAL, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BTN_TOTAL, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    int ticketCost;
    private void BTN_TOTALActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_TOTALActionPerformed
        String tic_selec = TXT_TIPO.getText().trim().toUpperCase();
        int CANTIDAD = Integer.parseInt(TXT_CANT.getText());

        if (tic_selec.equals("1")) {
            ticketCost = 25 * CANTIDAD;
        } else if (tic_selec.equals("2")) {
            ticketCost = 70 * CANTIDAD;
        } else {
            JOptionPane.showMessageDialog(null, "TICKET INCORRECTO", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        TXT_TOTAL.setText(String.valueOf(ticketCost));    }//GEN-LAST:event_BTN_TOTALActionPerformed

    private void TXT_TOTALActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXT_TOTALActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXT_TOTALActionPerformed

    private void TXT_TIPOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXT_TIPOActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXT_TIPOActionPerformed

    private void TXT_CANTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXT_CANTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXT_CANTActionPerformed

    private void BTN_SALIRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_SALIRActionPerformed
        System.exit(0);
    }//GEN-LAST:event_BTN_SALIRActionPerformed

    private void BTN_BORActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_BORActionPerformed
        TXT_TIPO.setText("");
        TXT_CANT.setText("");
        TXT_TOTAL.setText("");    }//GEN-LAST:event_BTN_BORActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tarea_13.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tarea_13.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tarea_13.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tarea_13.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tarea_13().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTN_BOR;
    private javax.swing.JButton BTN_SALIR;
    private javax.swing.JButton BTN_TOTAL;
    private javax.swing.JLabel LB_NOR;
    private javax.swing.JLabel LB_PREM;
    private javax.swing.JTextField TXT_CANT;
    private javax.swing.JTextField TXT_TIPO;
    private javax.swing.JTextField TXT_TOTAL;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
