/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Ejercicios;

import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author Academico
 */
public class Ejercicio_2 extends javax.swing.JFrame {
    /**
     * Creates new form Ejercicio_2
     */
    public Ejercicio_2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        labelr = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        NUM1 = new javax.swing.JTextField();
        NUM2 = new javax.swing.JTextField();
        RESU = new javax.swing.JTextField();
        SUM = new javax.swing.JButton();
        NUEVO = new javax.swing.JButton();
        SALIR = new javax.swing.JButton();
        opcion = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setText("OPERACIONES BÁSICAS");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("PRIMER NÚMERO");

        labelr.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        labelr.setText("SEGUNDO NÚMERO");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("RESULTADO");

        NUM1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        NUM1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NUM1ActionPerformed(evt);
            }
        });

        NUM2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        NUM2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NUM2ActionPerformed(evt);
            }
        });

        RESU.setEditable(false);
        RESU.setBackground(new java.awt.Color(204, 204, 204));
        RESU.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        RESU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RESUActionPerformed(evt);
            }
        });

        SUM.setBackground(new java.awt.Color(0, 204, 0));
        SUM.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        SUM.setText("OPERAR");
        SUM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SUMActionPerformed(evt);
            }
        });

        NUEVO.setBackground(new java.awt.Color(255, 255, 0));
        NUEVO.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        NUEVO.setText("NUEVO");
        NUEVO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NUEVOActionPerformed(evt);
            }
        });

        SALIR.setBackground(new java.awt.Color(204, 51, 0));
        SALIR.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        SALIR.setText("SALIR");
        SALIR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SALIRActionPerformed(evt);
            }
        });

        opcion.setBackground(new java.awt.Color(204, 255, 255));
        opcion.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        opcion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Suma", "Resta", "Multiplicación", "División", "Potencia", "Raíz cuadrada" }));
        opcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(labelr)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(NUM1, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NUM2, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RESU, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(SUM, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(NUEVO, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SALIR, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(67, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(opcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(50, 50, 50))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel1)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(3, 3, 3)
                        .addComponent(NUM1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(opcion, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(labelr)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(NUM2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(SUM, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(NUEVO, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(13, 13, 13)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SALIR, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RESU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NUM1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NUM1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NUM1ActionPerformed

    private void NUM2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NUM2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NUM2ActionPerformed

    private void RESUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RESUActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RESUActionPerformed

    private void SUMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SUMActionPerformed
        // TODO add your handling code here:
        if (NUM1.getText().isEmpty() || NUM2.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Ingresa todos los cuadros.");
        }else{
            if(null != opcion.getSelectedItem().toString())switch (opcion.getSelectedItem().toString()) {
                case "Suma" -> RESU.setText(Integer.toString(Integer.parseInt(NUM1.getText()) + Integer.parseInt(NUM2.getText())));
                case "Resta" -> RESU.setText(Integer.toString(Integer.parseInt(NUM1.getText()) - Integer.parseInt(NUM2.getText())));
                case "Multiplicación" -> RESU.setText(Integer.toString(Integer.parseInt(NUM1.getText()) * Integer.parseInt(NUM2.getText())));
                case "División" -> RESU.setText(Integer.toString(Integer.parseInt(NUM1.getText()) / Integer.parseInt(NUM2.getText())));
                case "Potencia" -> RESU.setText(Double.toString(Math.pow(Double.parseDouble(NUM1.getText()), Double.parseDouble(NUM2.getText()))));
                case "Raíz cuadrada" -> RESU.setText(Double.toString(Math.sqrt(Double.parseDouble(NUM1.getText()) + Double.parseDouble(NUM2.getText()))));
            }
            NUM1.setBackground(Color.gray);
            NUM2.setBackground(Color.gray);
            NUM1.setEditable(false);
            NUM2.setEditable(false);
        }
    }//GEN-LAST:event_SUMActionPerformed

    private void NUEVOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NUEVOActionPerformed
        // TODO add your handling code here
        NUM1.setBackground(Color.white);
        NUM2.setBackground(Color.white);
        NUM1.setText(null);
        NUM2.setText(null);
        RESU.setText(null);
        NUM1.setEditable(true);
        NUM2.setEditable(true);
    }//GEN-LAST:event_NUEVOActionPerformed

    private void SALIRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SALIRActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_SALIRActionPerformed

    private void opcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_opcionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ejercicio_2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ejercicio_2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ejercicio_2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ejercicio_2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ejercicio_2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton NUEVO;
    private javax.swing.JTextField NUM1;
    private javax.swing.JTextField NUM2;
    private javax.swing.JTextField RESU;
    private javax.swing.JButton SALIR;
    private javax.swing.JButton SUM;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel labelr;
    private javax.swing.JComboBox<String> opcion;
    // End of variables declaration//GEN-END:variables
}
